### ISSUE TITLE
Can i use ur app?

### ISSUE THREAD

**Issue by lirshani** [MikeCoder96/HappyLighting-py#1]
Can i use ur app? or do u offer service for brands?

**Comment by MikeCoder96** [comment]
The python contains useful method to control, i think, most chinese controller.
You can use Windows App "other repo in my acc" or you can customize this python script. 
If you want a private service, DM me.

**Comment by lirshani** [comment]
Yeah i would really like to hear about your service,
Can you please let me know how can i send you DM in here?

**Comment by MikeCoder96** [comment]
Reach me on discord for instant messaging:
REDACTED

**Comment by lirshani** [comment]
hi i have sent you friend request
