### ISSUE TITLE
Where are the preset pattern defined

### ISSUE THREAD

**Issue by BenKimerian** [MikeCoder96/HappyLighting-py#10]
Hi,

I would like to create a new preset (pulsating green/purple) as a training but i do not find where the presets are defined. I am not used to python and this kind of coding.

Thank you

**Comment by MikeCoder96** [comment]
Here an example: https://github.com/MikeCoder96/HappyLighting-py/blob/custom_mode_test/LEDStripController/Plugins/custommode_example.hpm

Here the Python method: https://github.com/MikeCoder96/HappyLighting-py/blob/custom_mode_test/LEDStripController/CustomMode.py

Consider it as a test
