### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by GoldenMelky** [MikeCoder96/HappyLighting-py#18]
after using this program for a while, i wanted to share some features that i propose:

- [ ] #21
- [x] when scanning for devices it show a loading icon
- [x] when closing the program it auto disconnects the connected device
- [x] #20

**Comment by MikeCoder96** [comment]
The task _uploading an audio file as the microphone feature (and playback to the pc's speakers)_ will not be added due to the fact you have to play the music from the program itself and it require player implementation.
