### ISSUE TITLE
issuses reporting

### ISSUE THREAD

**Issue by GoldenMelky** [MikeCoder96/HappyLighting-py#19]
after using this program for a while, i wanted to share some bugs that i want to report

- [x] in linux, i had to remove the `from ctypes import windll` and all its references (line 359 and 360) from `pyhl.py`
```
Traceback (most recent call last):
  File "/home/golden/Desktop/HappyLighting-py-master/LEDStripController/pyhl.py", line 18, in <module>
    from ctypes import windll
ImportError: cannot import name 'windll' from 'ctypes' (/usr/lib/python3.11/ctypes/__init__.py)
```
- [x] if a device is already connected to the pc, when the program is scanning for devices, the connected device isn't showing up
- [x] when sliding the speed slider when it isn't in a compatible mode, the program crashes
```
Traceback (most recent call last):
  File "/home/golden/Desktop/HappyLighting-py-master/LEDStripController/pyhl.py", line 242, in changeSpeed
    if isModeUsed:
       ^^^^^^^^^^
NameError: name 'isModeUsed' is not defined
```
- [x] when selecting both the local mic and the device mic the program crashes (some times) (i suggest to replace the checkboxes with radio buttons)

**Comment by MikeCoder96** [comment]
_if a device is already connected to the pc, when the program is scanning for devices, the connected device isn't showing up_
The chip inside the controller stop to be visible so is not a bug of the application

**Comment by GoldenMelky** [comment]
you could make the program disconnects all the devices when the window closes

**Comment by MikeCoder96** [comment]
implemented as requested in the other issue

**Comment by GoldenMelky** [comment]
right, I forgot about it
