### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dontbanmeplz** [MikeCoder96/HappyLighting-py#2]
im struggling with this program, my device shows up in like 1/15 scans. How do I get the UUID? Tried to get it from android but thats broken too. Any help would be apreceated. Chis#8122

**Comment by MikeCoder96** [comment]
Check this:
https://bleak.readthedocs.io/en/latest/scanning.html

**Comment by dontbanmeplz** [comment]
I actually got it working after awhile, but do you know anything about the music function with the lights?

**Comment by MikeCoder96** [comment]
The IR receiver contains 2 ways to control ligths from music.
1) A mic is integrated inside IR and use an inside chip to control light with music
2) The app use a Java Library to analyze the music and control the light with it.

You can control light too using python if you know how to manage a python sound library

**Comment by dontbanmeplz** [comment]
Yeah rn im using your code with a flask server on a raspberry pi to control the lights remotely, all the sound libraries i try to install just don't agree with whatever hardware i have

**Comment by MikeCoder96** [comment]
You can try to ask on a rpi Community

**Comment by dontbanmeplz** [comment]
where is that java library?

**Comment by MikeCoder96** [comment]
This is a python application. If you need Java package for android/desktop app, you have to create the communication by yourself

**Comment by dontbanmeplz** [comment]
ik that, but do you know where that java library is?

**Comment by MikeCoder96** [comment]
Idk what you talking about 😅
