### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by tristanplsrd** [MikeCoder96/HappyLighting-py#22]
Hello im very interest about the app but idk how to install it can u do a tutorial please ?

**Comment by read-0nly** [comment]
It's a bit complicated, especially since it depends on QT - I'm not the original dev but could try to whip up some instructions for you this weekend, I lost my own install of it

**Comment by MikeCoder96** [comment]
I'm working on create run file for linux (bash) and windows (powershell/cmd).
Unfortunately the time is my enemy so i cannot release updates very fast but I promise that in these days I will release an update with these run files and a little tutorial on how to run it and how the app works

**Comment by MikeCoder96** [comment]
Tutorial is now available on readme. Also, an executable is available in artifacts [here](https://github.com/MikeCoder96/HappyLighting-py/actions), there are 2 available versions that are for Linux and for Windows.
Linux is not tested unfortunate so, feel free to try and open new issue in case it not work.
