### ISSUE TITLE
UWP version

### ISSUE THREAD

**Issue by subashz** [MikeCoder96/HappyLighting-py#4]
there seems to be like windows version but could not found it. Also, what's the c++ / hex equivalent of controlling the led. I tried converting bytearray to hex equivalent but failed. I am trying to control the lighting via Bluetoothctl and gatt write? any help will really be appreciated.

**Comment by MikeCoder96** [comment]
the UWP version was deleted because not stable and very poor customizable cause of UWP limitation.
Show me how you are trying to write gatt in C++

**Comment by subashz** [comment]
Can you help me with the question : https://stackoverflow.com/questions/73417472/c-bluetoothctl-equivalent-code-of-python. 
I am trying to use this https://github.com/fusionhuh/wava and https://github.com/psychogenic/gattlibpp for making the led-strip light reacts to the music.  Some wava inspired post: (https://www.reddit.com/r/unixporn/comments/wq9iau/oc_wava_a_colorful_audio_visualizer_for_pulseaudio/)

Bluetoothctl equivaent will be something like this:
`./read_write 6E:05:A2:00:08:62 write 0000ffd1-0000-1000-8000-00805f9b34fb 56aa000019f0aa`

**Comment by MikeCoder96** [comment]
I will try to help you later.
Just to know, the music mode is W.I.P and today will be pushed first branch with early implementation 

EDIT:
try:
`./read_write 6E:05:A2:00:08:62 write 0000ffd1-0000-1000-8000-00805f9b34fb 0x56aa000019f0aa`
@subashz

**Comment by MikeCoder96** [comment]
@subashz 
try this [commit](https://github.com/MikeCoder96/HappyLighting-py/commit/801f22cc5f2ccddd9ba3ccf3dfc7ecf78b535177)
It is a early stage of implementation, need a lot of work to improve the output but at least it work.
You're welcome to contribute.

**Comment by MikeCoder96** [comment]
Closing for no update
