### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by SwadowMaster** [MikeCoder96/HappyLighting-py#9]
How can i use this?

**Comment by MikeCoder96** [comment]
You have to execute main.py with python and a interface will popup. From there it will be easy.

**Comment by SwadowMaster** [comment]
where is main.py?

**Comment by SwadowMaster** [comment]
![image](https://user-images.githubusercontent.com/72133740/214688862-a46bd084-50fd-4862-b784-4b007dc26ad5.png)

**Comment by MikeCoder96** [comment]
Sorry, i mean pyhl.py

**Comment by SwadowMaster** [comment]
![image](https://user-images.githubusercontent.com/72133740/214689878-aea93d6f-cdd1-4381-9baa-b9ddc6919cdd.png)

**Comment by MikeCoder96** [comment]
You have to install all requirements it ask. Qt is the first you need and after follow the requirement via errors. I will add requirements.txt soon

**Comment by SwadowMaster** [comment]
ok i will try to install it

**Comment by SwadowMaster** [comment]
[requirements.txt](https://github.com/MikeCoder96/HappyLighting-py/files/10504226/requirements.txt)
Here is a requirements list
